### PR TITLE
#6 - Fix missing SOQL fields

### PR DESCRIPTION
**Pull request by nebc-jasonfung**
This addresses: https://github.com/aidan-harding/nebula-object-transformer/issues/6

### CODE REVIEW

**Comment by nebc-jasonfung** [comment]
@aidan-harding - Had to fork this repo, so making a PR for this. Also not able to unit test this as the error occurs when querying for the orgs `Transformation_Field__mdt` via the class constructor. I guess that's why `TransformationTest.sillyCoverage()` exists. If you agree, I'll go ahead and build a new package and update the readme.

**Comment by aidan-harding** [comment]
Hi Jason,

Yes, I agree. I recall now that I introduced this test when I hit the same error of unqueried fields from the forward `Transformation` class. But, of course, you can't really test that in a scratch org because the lazy iterator doesn't read the fields when there are no CMDT records in the scratch org. I guess we could add an unpackaged directory to the repo, then scratch orgs for a dev working on the package could have a Transformation defined that is not part of the package. Then that would give us a failing test that your code change would fix. 

If you have the time/inclination, then you could add that unpackaged directory with one simple transformation (and reverse defined). No worries if not, because this code now clearly works.

Either way, feel free to build a new package and add the updated project file to this PR. Then I'll merge it and tag the new release.

**Comment by nebc-jasonfung** [comment]
Hi @aidan-harding,

I've added an unpackaged directory and new tests as per your suggestions and also updated the project file. Let me know if you'd like me to tweak any naming conventions.

**Review by aidan-harding — CHANGES_REQUESTED** [review]
You can remove the sillyCoverage() test now because that one is covered by your new tests

**Comment by aidan-harding** [comment]
Thanks, Jason. Sorry for the pedantry (although you did leave the door open by asking about naming conventions 😉), but can you name the directory unpackaged instead of unpackaged-tests? That's what we normally call it, and it would be good for consistency. 

Finally, you'll need to increment the version number to 1.0.2. If you run `sfdx force:package:version:list --packages 0Ho6M0000008OKzSAM`, you'll see that there's already a released version of 1.0.1.

**Comment by nebc-jasonfung** [comment]
No worries - I've made the updates and also promoted the latest package version.

**Review by aidan-harding — APPROVED** [review]

**Pull request merged**
